version: '3.8'

services:
  api:
    build: .
    container_name: taskmanagement-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Managerment;User Id=sa;Password=YourStrong@Pass123;Trust Server Certificate=True
      - JWT__SecretKey=SuperkeyPRoWith256BitsAnd32BytesStringVip456
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=TaskMgmt_
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanagement-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Pass123
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Pass123" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: taskmanagement-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  sqlserver_data:
  redis_data:
